[release]
output = "dist/release"
include = [
  "README.rst",
  "pyproject.toml",
  "docs",
  "labs",
  "sources.lock",
]
exclude = [
  "docs/_build/**",
  "labs/**/__pycache__/**",
  "**/*.pyc",
  "**/.DS_Store",
]
